services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=masteruser
      - POSTGRES_PASSWORD=mypassword345.
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8000 || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 3
  db:
    image: postgres
    container_name: db
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
  api:
#    env_file:
#      - ../api_container/.env
#    environment:
#     - LOCAL_HOME=/run/desktop/mnt/host/c/Users/jszub
    build: ../api_container
    deploy:
      resources:
        limits:
          cpus: '1.50'
          memory: 400M
        reservations:
          cpus: '0.50'
          memory: 128M
    volumes:
#      - ../api_container:/code
      - ${LOCAL_HOME}/.aws:/home/python/.aws
    ports:
      - "80:80"
    restart: always
    depends_on:
      web:
        condition: service_healthy
