# Generated by Django 4.1.4 on 2023-06-14 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_joined_date_member_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(max_length=128)),
                ('mark', models.CharField(max_length=128)),
                ('size', models.CharField(max_length=8)),
                ('color', models.CharField(max_length=128)),
                ('wear', models.CharField(max_length=128)),
            ],
        ),
    ]
