# Generated by Django 4.1.4 on 2023-06-19 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_item_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='photo',
            field=models.ImageField(default='Unknown', upload_to=''),
        ),
    ]
