# Generated by Django 4.1.4 on 2023-07-03 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_rename_image_item_image_1_remove_item_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image_1',
            field=models.ImageField(upload_to='item_images/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_2',
            field=models.ImageField(upload_to='item_images/'),
        ),
    ]
