# Generated by Django 4.1.4 on 2023-07-03 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_alter_item_image_1_alter_item_image_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image_1',
            field=models.ImageField(null=True, upload_to='item_images/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_2',
            field=models.ImageField(null=True, upload_to='item_images/'),
        ),
    ]
