# Generated by Django 4.1.4 on 2023-07-04 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_alter_item_image_1_alter_item_image_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image_1',
        ),
        migrations.RemoveField(
            model_name='item',
            name='image_2',
        ),
    ]
