# Generated by Django 4.1.4 on 2023-07-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_remove_item_image_1_remove_item_image_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Image1',
            field=models.ImageField(default='images/None/no-img.jpg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='item',
            name='Image2',
            field=models.ImageField(default='images/None/no-img.jpg', upload_to='images/'),
        ),
    ]
